version: "3"
services:
  server-app:
    build: ./framework-api
    image: framework-api
    deploy:
      replicas: 1
      # resources:
      #   limits:
      #     cpus: "0.1"
      #     memory: 50M
      restart_policy:
        condition: on-failure
    ports:
      - "3000:3000"
    networks:
      - intranet
  db:
    build: ./framework-database
    image: neo4j-database
    deploy:
      replicas: 1
      #   resources:
      #     limits:
      #       cpus: "0.1"
      #       memory: 50M
      restart_policy:
        condition: on-failure
    ports:
      - "7474:7474"
      - "7687:7687"
    networks:
      - intranet
networks:
  intranet:
